networks:
    whatbug:

volumes:
    dbdata:
    pgadmindata:

services:
  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: src/WebUI/Dockerfile
    environment:
      WhatBug__Accounts__RegistrationEnabled: "${WhatBug__Accounts__RegistrationEnabled:-true}"
      WhatBug__Accounts__DemoEnabled: "${WhatBug__Accounts__DemoEnabled:-false}"
      WhatBug__Accounts__DemoUsername: "${WhatBug__Accounts__DemoUsername:-}"
      ConnectionStrings__WhatBugDatabase: "${ConnectionStrings__WhatBugDatabase:-Host=postgres;Database=WhatBug;Username=postgres;Password=admin}"
      ConnectionStrings__IdentityDatabase: "${ConnectionStrings__IdentityDatabase:-Host=postgres;Database=WhatBugIdentity;Username=postgres;Password=admin}"
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - whatbug
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /var/lib/postgressql/data
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "dbdata:/var/lib/postgressql/data"
    networks:
        - whatbug
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U $$POSTGRES_USER -d postgres"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s
    restart: unless-stopped