// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhatBug.Persistence;

#nullable disable

namespace WhatBug.Persistence.Migrations
{
    [DbContext(typeof(WhatBugDbContext))]
    [Migration("20211116150838_AddRoleAssignPermissions")]
    partial class AddRoleAssignPermissions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhatBug.Domain.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("IssueId")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "White"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chiffon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Frost"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tan"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Buttermilk"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Beige"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Oat"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cookie"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Latte"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lemon"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Honey"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Apricot"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Blush"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Rose"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Candy"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Cherry"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Fushcia"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Hotpink"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Magenta"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Lilac"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Iris"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Amethyst"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Violet"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Sky"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Sapphire"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Cerulean"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Cobalt"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Navy"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Mint"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Seafoam"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Lime"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Olive"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Pear"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Pickle"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Shamrock"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Emerald"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Basil"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Tortilla"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Peanut"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Tawny"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Caramel"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Mocha"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Hickory"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Cloud"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Coin"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Ash"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Gray"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Pewter"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Smoke"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Slate"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Black"
                        });
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Icon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("WebName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Icons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ArrowUp",
                            WebName = "arrow-up"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ArrowDown",
                            WebName = "arrow-down"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ArrowLeft",
                            WebName = "arrow-left"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ArrowRight",
                            WebName = "arrow-right"
                        },
                        new
                        {
                            Id = 5,
                            Name = "CircleArrowUp",
                            WebName = "arrow-circle-up"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CircleArrowDown",
                            WebName = "arrow-circle-down"
                        },
                        new
                        {
                            Id = 7,
                            Name = "CircleArrowLeft",
                            WebName = "arrow-circle-left"
                        },
                        new
                        {
                            Id = 8,
                            Name = "CircleArrowRight",
                            WebName = "arrow-circle-right"
                        },
                        new
                        {
                            Id = 9,
                            Name = "ChevronUp",
                            WebName = "chevron-up"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ChevronDown",
                            WebName = "chevron-down"
                        },
                        new
                        {
                            Id = 11,
                            Name = "ChevronLeft",
                            WebName = "chevron-left"
                        },
                        new
                        {
                            Id = 12,
                            Name = "ChevronRight",
                            WebName = "chevron-right"
                        },
                        new
                        {
                            Id = 13,
                            Name = "AngleUp",
                            WebName = "angle-up"
                        },
                        new
                        {
                            Id = 14,
                            Name = "AngleDown",
                            WebName = "angle-down"
                        },
                        new
                        {
                            Id = 15,
                            Name = "AngleLeft",
                            WebName = "angle-left"
                        },
                        new
                        {
                            Id = 16,
                            Name = "AngleRight",
                            WebName = "angle-right"
                        },
                        new
                        {
                            Id = 17,
                            Name = "AnglesUp",
                            WebName = "angles-up"
                        },
                        new
                        {
                            Id = 18,
                            Name = "AnglesDown",
                            WebName = "angles-down"
                        },
                        new
                        {
                            Id = 19,
                            Name = "AnglesLeft",
                            WebName = "angles-left"
                        },
                        new
                        {
                            Id = 20,
                            Name = "AnglesRight",
                            WebName = "angles-right"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Exclaimaton",
                            WebName = "exclamation"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Circle Exclamation",
                            WebName = "exclamation-circle"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Triangle Exclamation",
                            WebName = "exclamation-triangle"
                        },
                        new
                        {
                            Id = 24,
                            Name = "X Mark",
                            WebName = "x-mark"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Ban",
                            WebName = "ban"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Equals",
                            WebName = "equals"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Bug",
                            WebName = "bug"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Square Plus",
                            WebName = "plus-square"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Square Check",
                            WebName = "check-square"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Square Caret Up",
                            WebName = "caret-up-square"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Square Caret Down",
                            WebName = "caret-down-square"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Square Caret Left",
                            WebName = "caret-left-square"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Square Caret Right",
                            WebName = "caret-right-square"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Pen",
                            WebName = "pen"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Plus",
                            WebName = "plus"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Information",
                            WebName = "information"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Circle",
                            WebName = "circle"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Wave Square",
                            WebName = "wave-square"
                        });
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Issue", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IssueStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("IssueTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("ReporterId")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("IssueStatusId");

                    b.HasIndex("IssueTypeId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.IssueComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("IssueId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueComments");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.IssueStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IssueStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Backlog"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ToDo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Done"
                        });
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.IssueType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<int>("IconId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("IconId");

                    b.ToTable("IssueTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 34,
                            IconId = 29,
                            Name = "Task"
                        },
                        new
                        {
                            Id = 2,
                            ColorId = 19,
                            IconId = 27,
                            Name = "Bug"
                        });
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Create new projects.",
                            Name = "Create Project",
                            Type = "Global"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Delete existing projects.",
                            Name = "Delete Project",
                            Type = "Global"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Grant and/or deny user-level permissions.",
                            Name = "Manage User Permissions",
                            Type = "Global"
                        },
                        new
                        {
                            Id = 4,
                            Description = "View all projects in WhatBug. Users without this permission must be a member of a project to view it.",
                            Name = "View All Projects",
                            Type = "Global"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Create, edit and delete project roles used by permission schemes.",
                            Name = "Manage Project Roles",
                            Type = "Global"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Create, edit and delete permission schemes.",
                            Name = "Manage Permission Schemes",
                            Type = "Global"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Create, edit and delete priorities.",
                            Name = "Manage Priorities",
                            Type = "Global"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Create, edit and delete priority schemes.",
                            Name = "Manage Priority Schemes",
                            Type = "Global"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Create new issues within a project.",
                            Name = "Create Issue",
                            Type = "Project"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Edit existing issues within a project.",
                            Name = "Edit Issue",
                            Type = "Project"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Delete issues within a project.",
                            Name = "Delete Issue",
                            Type = "Project"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Assign users to roles within a project.",
                            Name = "Assign User Roles",
                            Type = "Project"
                        },
                        new
                        {
                            Id = 13,
                            Description = "View project members and their roles.",
                            Name = "View Project Members",
                            Type = "Project"
                        });
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.PermissionScheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PermissionSchemes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 0,
                            Description = "The default permission scheme used by all projects without any other scheme assigned.",
                            IsDefault = true,
                            LastModifiedBy = 0,
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.PermissionSchemeRolePermission", b =>
                {
                    b.Property<int>("PermissionSchemeId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("PermissionSchemeId", "RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("PermissionSchemeRolePermissions");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IconId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("IconId");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 63,
                            Description = "The default priority used by all issues without any other priority assigned.",
                            IconId = 38,
                            IsDefault = true,
                            Name = "Default",
                            Order = 0
                        });
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.PriorityScheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PrioritySchemes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The default priority scheme used by all projects without any other scheme assigned.",
                            IsDefault = true,
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.PrioritySchemePriority", b =>
                {
                    b.Property<int>("PrioritySchemeId")
                        .HasColumnType("integer");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer");

                    b.HasKey("PrioritySchemeId", "PriorityId");

                    b.HasIndex("PriorityId");

                    b.ToTable("PrioritySchemePriorities");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IssueCounter")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PermissionSchemeId")
                        .HasColumnType("integer");

                    b.Property<int>("PrioritySchemeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionSchemeId");

                    b.HasIndex("PrioritySchemeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.ProjectRoleUser", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectId", "RoleId", "UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectRoleUsers");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("WhatBug.Domain.Entities.Issue", "Issue")
                        .WithMany("Attachments")
                        .HasForeignKey("IssueId");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Issue", b =>
                {
                    b.HasOne("WhatBug.Domain.Entities.User", "Assignee")
                        .WithMany("AssignedIssues")
                        .HasForeignKey("AssigneeId");

                    b.HasOne("WhatBug.Domain.Entities.IssueStatus", "IssueStatus")
                        .WithMany()
                        .HasForeignKey("IssueStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatBug.Domain.Entities.IssueType", "IssueType")
                        .WithMany()
                        .HasForeignKey("IssueTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhatBug.Domain.Entities.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatBug.Domain.Entities.Project", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatBug.Domain.Entities.User", "Reporter")
                        .WithMany("ReportedIssues")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("IssueStatus");

                    b.Navigation("IssueType");

                    b.Navigation("Priority");

                    b.Navigation("Project");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.IssueComment", b =>
                {
                    b.HasOne("WhatBug.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatBug.Domain.Entities.Issue", "Issue")
                        .WithMany("Comments")
                        .HasForeignKey("IssueId");

                    b.Navigation("Author");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.IssueType", b =>
                {
                    b.HasOne("WhatBug.Domain.Entities.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatBug.Domain.Entities.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.PermissionSchemeRolePermission", b =>
                {
                    b.HasOne("WhatBug.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatBug.Domain.Entities.PermissionScheme", "PermissionScheme")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatBug.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("PermissionScheme");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Priority", b =>
                {
                    b.HasOne("WhatBug.Domain.Entities.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatBug.Domain.Entities.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.PrioritySchemePriority", b =>
                {
                    b.HasOne("WhatBug.Domain.Entities.Priority", "Priority")
                        .WithMany("PrioritySchemes")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatBug.Domain.Entities.PriorityScheme", "PriorityScheme")
                        .WithMany("Priorities")
                        .HasForeignKey("PrioritySchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Priority");

                    b.Navigation("PriorityScheme");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Project", b =>
                {
                    b.HasOne("WhatBug.Domain.Entities.PermissionScheme", "PermissionScheme")
                        .WithMany()
                        .HasForeignKey("PermissionSchemeId");

                    b.HasOne("WhatBug.Domain.Entities.PriorityScheme", "PriorityScheme")
                        .WithMany("Projects")
                        .HasForeignKey("PrioritySchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionScheme");

                    b.Navigation("PriorityScheme");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.ProjectRoleUser", b =>
                {
                    b.HasOne("WhatBug.Domain.Entities.Project", "Project")
                        .WithMany("RoleUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatBug.Domain.Entities.Role", "Role")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatBug.Domain.Entities.User", "User")
                        .WithMany("ProjectRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("WhatBug.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatBug.Domain.Entities.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Issue", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.PermissionScheme", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Priority", b =>
                {
                    b.Navigation("PrioritySchemes");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.PriorityScheme", b =>
                {
                    b.Navigation("Priorities");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Project", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("RoleUsers");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.Role", b =>
                {
                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("WhatBug.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedIssues");

                    b.Navigation("ProjectRoles");

                    b.Navigation("ReportedIssues");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
